# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for more information:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# https://containers.dev/guide/dependabot

version: 2
updates:
  # Maintain devcontainer dependencies
  - package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "devcontainer"
  
  # Maintain npm dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    groups:
      # Group all non-major updates together
      minor-and-patch:
        update-types:
          - "minor"
          - "patch"
    versioning-strategy: increase
  
  # Maintain GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
    labels:
      - "dependencies"
      - "github-actions"
